# Generated by Django 5.0 on 2023-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('light-red', 'Rojo'), ('light-green', 'Verde'), ('light-blue', 'Azul'), ('light-yellow', 'Amarillo')], default='light-red', max_length=20),
        ),
    ]
