# Generated by Django 5.0 on 2023-12-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
